site_name: OpenPyrojet
site_description: Open source/hardware thermal spraying 3D printer
site_author: OpenPyrojet
site_url: https://openpyrojet.com
theme: readthedocs
extra_css:
  - css/extra.css
docs_dir: source
site_dir: docs
pages:
  - 'Introduction': 'index.md'
  - 'Project Brief': 'project-brief.md'
  - 'Roadmap': 'roadmap.md'
  - 'Feedstock': 'feedstock.md'
